from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional


@dataclass
class DataConfig:
    corpus_path: str = "data/flat_corpus.json"
    corpus_metadata_path: str = "data/corpus_metadata.json"
    doc_embeddings_path: str = "data/doc_embeddings.pt"
    qa_pairs_path: str = "data/generated_qa_pairs.json"
    reward_matrix_path: str = "data/reward_matrix.json"
    squad_subset_path: str = "data/squad_dev_subset.json"
    squad_full_path: str = "data/squad_dev_pairs.json"
    # Paths for context-aware SQuAD evaluation (generated by setup_squad_eval.py)
    squad_eval_pairs_path: str = "data/squad_eval_pairs.json"
    squad_contexts_path: str = "data/squad_contexts.json"
    squad_embeddings_path: str = "data/squad_doc_embeddings.pt"
    external_dataset_paths: List[str] = field(default_factory=list)
    embedding_model: str = "sentence-transformers/all-MiniLM-L6-v2"
    embedding_dim: int = 384
    regenerate_embeddings: bool = False
    max_corpus_docs: int = 0


@dataclass
class BenchmarkDatasetConfig:
    use_triviaqa: bool = False
    triviaqa_split: str = "validation"
    triviaqa_subset_n: int = 500
    use_natural_questions: bool = False
    nq_split: str = "validation"
    nq_subset_n: int = 500
    use_mlqa: bool = False
    mlqa_languages: List[str] = field(default_factory=lambda: ["en", "de", "es", "ar", "hi", "zh", "vi"])
    mlqa_subset_n: int = 200
    cache_dir: str = "data/hf_cache"


@dataclass
class ModelConfig:
    doc_emb_dim: int = 384
    hidden_dim: int = 256
    dropout: float = 0.1
    use_layer_norm: bool = True
    use_residual: bool = True


@dataclass
class AblationConfig:
    use_supervised_warmup: bool = True
    use_reward_shaping: bool = True
    use_curriculum_learning: bool = True
    # ── Journal-extension flags ───────────────────────────────────────────────
    use_contrastive_warmup: bool = False          # CSP: contrastive pre-training before SL
    use_diversity_reward: bool = False            # DAR: diversity-aware reward shaping
    use_adaptive_budget: bool = False             # ADB: adaptive document-budget head
    use_query_complexity_curriculum: bool = False # QCC: query-complexity-aware curriculum


@dataclass
class TrainingConfig:
    seed: int = 42
    device: str = "auto"
    supervised_epochs: int = 150
    supervised_lr: float = 5e-5
    supervised_weight_decay: float = 1e-4
    supervised_batch_size: int = 32
    supervised_checkpoint: str = "models/sras_selector_supervised.pt"
    ppo_epochs: int = 25
    ppo_lr: float = 1e-5
    ppo_weight_decay: float = 1e-4
    ppo_batch_size: int = 8
    ppo_update_epochs: int = 4
    ppo_clip_eps: float = 0.2
    ppo_gamma: float = 0.99
    ppo_entropy_coef: float = 0.01
    ppo_grad_clip: float = 1.0
    top_k: int = 3
    curriculum_start_docs: int = 10
    curriculum_end_docs: int = 100
    curriculum_step_interval: int = 5
    curriculum_step_size: int = 5
    curriculum_schedule: str = "step"
    curriculum_fixed_docs: int = 30
    reward_f1_weight: float = 0.6
    reward_bertscore_weight: float = 0.4
    # ── Novel contribution hyper-parameters ──────────────────────────────────
    # Contrastive Selector Pre-training (CSP)
    contrastive_epochs: int = 20
    contrastive_lr: float = 1e-4
    contrastive_temperature: float = 0.07
    contrastive_n_negatives: int = 15
    contrastive_checkpoint: str = "models/sras_selector_contrastive.pt"
    # Diversity-Aware Reward (DAR): bumped from 0.15/0.10 to ensure the signal
    # is large enough relative to base reward (~0.34) to differentiate ablations
    diversity_reward_weight: float = 0.30
    coverage_reward_weight: float = 0.20
    # Adaptive Document Budget (ADB)
    adaptive_budget_min_k: int = 1
    adaptive_budget_max_k: int = 5
    # Query-Complexity Curriculum (QCC)
    qcc_tier1_epochs: int = 6   # epochs covering only easy (who/what) queries
    qcc_tier2_epochs: int = 15  # epochs adding medium (when/where) queries
    generator_model: str = "google/flan-t5-base"
    generator_max_input_len: int = 512
    generator_max_output_len: int = 128
    checkpoint_dir: str = "models"
    log_dir: str = "logs"
    results_dir: str = "results"
    resume_checkpoint: Optional[str] = None
    save_best: bool = True
    ablations: AblationConfig = field(default_factory=AblationConfig)


@dataclass
class BaselineConfig:
    use_bm25: bool = True
    use_dense: bool = True
    use_hybrid: bool = True
    use_dpr: bool = False              # DPR (Karpukhin et al. 2020); set True to include
    use_learned_ranker: bool = False
    hybrid_bm25_weight: float = 0.5
    dense_model: str = "sentence-transformers/all-MiniLM-L6-v2"
    dpr_cache_path: str = "data/dpr_doc_embeddings.pt"
    learned_ranker_checkpoint: Optional[str] = None
    learned_ranker_epochs: int = 10
    learned_ranker_lr: float = 1e-4
    learned_ranker_hidden_dim: int = 256
    # Modern compact dense retrievers (BGE-small-en, E5-small)
    use_bge_small: bool = False
    bge_small_model: str = "BAAI/bge-small-en-v1.5"
    bge_small_cache_path: str = "data/bge_small_doc_embeddings.pt"
    use_e5_small: bool = False
    e5_small_model: str = "intfloat/e5-small-v2"
    e5_small_cache_path: str = "data/e5_small_doc_embeddings.pt"


@dataclass
class CompressionConfig:
    use_quantization: bool = False
    quantization_dtype: str = "int8"
    use_pruning: bool = False
    pruning_amount: float = 0.3
    pruning_method: str = "magnitude"
    use_distillation: bool = False
    distillation_temperature: float = 4.0
    distillation_alpha: float = 0.5
    distillation_epochs: int = 20
    distillation_lr: float = 5e-5
    student_hidden_dim: int = 128
    output_dir: str = "models/compressed"


@dataclass
class RobustnessConfig:
    noise_rates: List[float] = field(default_factory=lambda: [0.0, 0.1, 0.2, 0.3, 0.5])
    redundant_rates: List[float] = field(default_factory=lambda: [0.0, 0.1, 0.2, 0.3])
    adversarial_rates: List[float] = field(default_factory=lambda: [0.0, 0.1, 0.2])
    domain_shift_categories: List[str] = field(default_factory=lambda: [
        "Law And Society", "Technology and Cybersecurity", "Philosophy And Ethics"
    ])
    n_trials: int = 3
    results_dir: str = "results/robustness"


@dataclass
class FailureAnalysisConfig:
    f1_failure_threshold: float = 0.1
    selector_hit_threshold: float = 0.1
    max_failure_cases: int = 100
    results_dir: str = "results/failure_analysis"


@dataclass
class DeploymentConfig:
    device: str = "cpu"
    n_warmup: int = 10
    n_iterations: int = 200
    measure_ram: bool = True
    measure_throughput: bool = True
    measure_energy: bool = True
    measure_thermal: bool = True
    measure_cpu_percent: bool = True
    thermal_interval_s: float = 0.5
    throughput_batch_sizes: List[int] = field(default_factory=lambda: [1, 4, 8, 16])
    candidate_pool_sizes: List[int] = field(default_factory=lambda: [10, 30, 50, 100])
    results_dir: str = "results/deployment"
    is_raspberry_pi: bool = False


@dataclass
class EvaluationConfig:
    seed: int = 42
    device: str = "auto"
    batch_size: int = 32
    top_k: int = 3
    candidate_pool_size: int = 30
    datasets: List[str] = field(default_factory=lambda: ["internal", "squad_eval"])
    results_dir: str = "results"
    figures_dir: str = "figures/sras_model_eval"
    metrics: List[str] = field(default_factory=lambda: ["relaxed_f1", "bertscore_f1", "exact_match"])
    generator_model: str = "google/flan-t5-base"
    generator_max_input_len: int = 512
    generator_max_output_len: int = 128
    noise_distractor_rate: float = 0.0
    redundant_distractor_rate: float = 0.0
    adversarial_distractor_rate: float = 0.0
    per_question_type_analysis: bool = True
    failure_analysis: bool = True
    run_baselines: bool = True
    ablation_variants: List[str] = field(default_factory=list)
    baseline: BaselineConfig = field(default_factory=BaselineConfig)
    benchmark_datasets: BenchmarkDatasetConfig = field(default_factory=BenchmarkDatasetConfig)
    failure: FailureAnalysisConfig = field(default_factory=FailureAnalysisConfig)
    robustness: RobustnessConfig = field(default_factory=RobustnessConfig)


@dataclass
class BenchmarkConfig:
    seed: int = 42
    device: str = "auto"
    n_warmup: int = 10
    n_iterations: int = 100
    candidate_pool_sizes: List[int] = field(default_factory=lambda: [10, 30, 50, 100])
    embedding_model: str = "sentence-transformers/all-MiniLM-L6-v2"
    corpus_metadata_path: str = "data/corpus_metadata.json"
    model_registry: Dict[str, str] = field(default_factory=lambda: {
        "ppo_base": "models/sras_selector_ppo_base.pt",
        "supervised": "models/sras_selector_supervised.pt",
        "ppo_nosw": "models/sras_selector_ppo_nosw.pt",
        "ppo_nors": "models/sras_selector_ppo_nors.pt",
        "ppo_nocl": "models/sras_selector_ppo_nocl.pt",
    })
    results_dir: str = "figures/sras_model_eval"
    deployment: DeploymentConfig = field(default_factory=DeploymentConfig)
    compression: CompressionConfig = field(default_factory=CompressionConfig)


@dataclass
class SRASConfig:
    name: str = "sras_ppo_base"
    data: DataConfig = field(default_factory=DataConfig)
    model: ModelConfig = field(default_factory=ModelConfig)
    training: TrainingConfig = field(default_factory=TrainingConfig)
    evaluation: EvaluationConfig = field(default_factory=EvaluationConfig)
    benchmark: BenchmarkConfig = field(default_factory=BenchmarkConfig)
